# SSL Certificate to CSR Generator

This project provides a Python script that:

1. Reads a list of domain names from a text file (`domain_list.txt`).
2. Connects to each domain via SSL/TLS and retrieves its certificate.
3. Extracts subject information and key extensions (e.g., SAN, KeyUsage).
4. Generates a new RSA private key and a CSR (Certificate Signing Request) using the extracted information.
5. Saves both the private key and the CSR to disk.

## Requirements
- Python 3.6+
- `cryptography` library

You can install required dependencies using:
```bash
pip install cryptography
```

## Usage
1. Create a `domain_list.txt` file in the project directory with one domain per line (e.g. `example.com`).
2. Run the script:
```bash
python ssl_cert_to_csr.py
```

## License
This project is licensed under the GNU General Public License v3.0 (GPLv3). See the [LICENSE](https://www.gnu.org/licenses/gpl-3.0.en.html) file for details.

## Disclaimer
This code was generated by an AI (ChatGPT by OpenAI). It is provided **as-is**, without any express or implied warranties. Use at your own risk, especially in security-sensitive or production environments.

